- hosts: all
  become: yes

  tasks:
    - debug:
        msg: >-
          Testing with Ansible {{ ansible_version.full }} using Python {{ ansible_facts.python_version }}
          on {{ ansible_facts.distribution }} {{ ansible_facts.distribution_version }}

    - import_role:
        name: gitlab_runner

    - name: Verify GitLab runner was installed
      command: gitlab-runner --version
      changed_when: no
      register: result

    - name: Check output
      assert:
        that:
          - "'Version' in result.stdout"
